"use client";

import { FormEvent, useState } from "react";
import { Edit3, KeyRound, Plus, ShieldCheck, Trash2, UsersRound } from "lucide-react";
import { apiFetch, formatDate, useAppData, useRemote, useToast } from "../client-utils";
import { EmptyState, ErrorState, Field, LoadingState, Modal, PageHeader } from "../ui";

type User = { id: string; username: string; name: string; departmentId: string; departmentName: string; roleId: string; roleName: string; mustChangePassword: boolean; lastLoginAt?: string; createdAt: string };
type Role = { id: string; name: string; description?: string; permissions: string[]; dataScope: "all" | "department"; isSystem: boolean; userCount: number };
type RoleData = { rows: Role[]; permissionGroups: Array<{ label: string; items: Array<{ key: string; label: string }> }> };

export function UsersView() {
  const { lookups, can, refreshLookups, user: currentUser } = useAppData(); const toast = useToast(); const { data, loading, error, reload } = useRemote<User[]>("/api/users"); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<User | null>(null); const [saving, setSaving] = useState(false); const [form, setForm] = useState({ username: "", name: "", password: "", departmentId: "", roleId: "", mustChangePassword: true });
  function show(item?: User) { setEditing(item || null); setForm(item ? { username: item.username, name: item.name, password: "", departmentId: item.departmentId, roleId: item.roleId, mustChangePassword: item.mustChangePassword } : { username: "", name: "", password: "", departmentId: lookups?.departments[0]?.id || "", roleId: lookups?.roles.find((role) => role.name !== "超级管理员")?.id || lookups?.roles[0]?.id || "", mustChangePassword: true }); setOpen(true); }
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); try { await apiFetch(editing ? `/api/users/${editing.id}` : "/api/users", { method: editing ? "PATCH" : "POST", body: JSON.stringify(form) }); toast(editing ? "账号已修改" : "账号已创建"); setOpen(false); await Promise.all([reload(), refreshLookups()]); } catch (reason) { toast(reason instanceof Error ? reason.message : "保存失败", "error"); } finally { setSaving(false); } }
  async function remove(item: User) { if (!confirm(`确定停用账号“${item.username}”吗？`)) return; try { await apiFetch(`/api/users/${item.id}`, { method: "DELETE" }); toast("账号已停用"); await reload(); } catch (reason) { toast(reason instanceof Error ? reason.message : "停用失败", "error"); } }
  return <><PageHeader eyebrow="一人一账号" title="账号管理" description="每个账号只属于一个部门和一个角色，权限随角色自动生效。" actions={can("users:manage") && <button className="button button-primary" onClick={() => show()}><Plus size={17} />创建账号</button>} />
    <section className="panel table-panel">{loading ? <LoadingState /> : error ? <ErrorState message={error} retry={reload} /> : !data?.length ? <EmptyState title="暂无账号" /> : <><div className="data-table-wrap"><table className="data-table"><thead><tr><th>姓名 / 账号</th><th>所属部门</th><th>角色</th><th>最后登录</th><th>状态</th><th /></tr></thead><tbody>{data.map((item) => <tr key={item.id}><td><div className="user-cell"><span className="avatar">{item.name.slice(0, 1)}</span><div><b>{item.name}</b><small>@{item.username}</small></div></div></td><td>{item.departmentName}</td><td><span className="role-chip"><ShieldCheck size={14} />{item.roleName}</span></td><td>{item.lastLoginAt ? formatDate(item.lastLoginAt, true) : "从未登录"}</td><td>{item.mustChangePassword ? <span className="soft-badge warning">首次登录需改密码</span> : <span className="soft-badge success">正常</span>}</td><td>{can("users:manage") && <div className="table-actions"><button className="icon-button" onClick={() => show(item)} title="编辑或重置密码"><Edit3 size={16} /></button>{item.id !== currentUser.id && <button className="icon-button danger" onClick={() => remove(item)} title="停用"><Trash2 size={16} /></button>}</div>}</td></tr>)}</tbody></table></div><div className="mobile-record-list">{data.map((item) => <article className="mobile-record compact" key={item.id}><div className="user-cell"><span className="avatar">{item.name.slice(0, 1)}</span><div><b>{item.name}</b><small>@{item.username} · {item.departmentName}</small></div></div><div className="table-actions"><button className="icon-button" onClick={() => show(item)}><Edit3 size={16} /></button></div></article>)}</div></>}</section>
    {open && <Modal title={editing ? `编辑账号 ${editing.username}` : "创建账号"} onClose={() => setOpen(false)}><form className="modal-form" onSubmit={submit}><div className="form-grid"><Field label="登录账号" required><input autoFocus value={form.username} onChange={(event) => setForm({ ...form, username: event.target.value })} /></Field><Field label="姓名" required><input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></Field><Field label="所属部门" required><select value={form.departmentId} onChange={(event) => setForm({ ...form, departmentId: event.target.value })}><option value="">请选择</option>{lookups?.departments.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></Field><Field label="角色" required><select value={form.roleId} onChange={(event) => setForm({ ...form, roleId: event.target.value })}><option value="">请选择</option>{lookups?.roles.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></Field><Field label={editing ? "重置密码" : "初始密码"} required={!editing} hint={editing ? "不修改密码请留空" : "至少 8 位，建议字母、数字和符号组合"} className="field-full"><div className="input-prefix"><KeyRound size={17} /><input type="password" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} required={!editing} /></div></Field></div><label className="switch-row"><input type="checkbox" checked={form.mustChangePassword} onChange={(event) => setForm({ ...form, mustChangePassword: event.target.checked })} /><span>下次登录时提醒修改密码</span></label><div className="modal-actions"><button type="button" className="button button-ghost" onClick={() => setOpen(false)}>取消</button><button className="button button-primary" disabled={saving}>{saving ? "保存中…" : "保存账号"}</button></div></form></Modal>}
  </>;
}

export function RolesView() {
  const { can, refreshLookups } = useAppData(); const toast = useToast(); const { data, loading, error, reload } = useRemote<RoleData>("/api/roles"); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<Role | null>(null); const [saving, setSaving] = useState(false); const [form, setForm] = useState({ name: "", description: "", permissions: [] as string[], dataScope: "department" as "all" | "department" });
  function show(item?: Role) { setEditing(item || null); setForm(item ? { name: item.name, description: item.description || "", permissions: item.permissions, dataScope: item.dataScope } : { name: "", description: "", permissions: ["dashboard:view", "products:view", "samples:view"], dataScope: "department" }); setOpen(true); }
  function toggle(key: string) { setForm((value) => ({ ...value, permissions: value.permissions.includes(key) ? value.permissions.filter((item) => item !== key) : [...value.permissions, key] })); }
  function toggleGroup(keys: string[]) { const all = keys.every((key) => form.permissions.includes(key)); setForm((value) => ({ ...value, permissions: all ? value.permissions.filter((key) => !keys.includes(key)) : Array.from(new Set([...value.permissions, ...keys])) })); }
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); try { await apiFetch(editing ? `/api/roles/${editing.id}` : "/api/roles", { method: editing ? "PATCH" : "POST", body: JSON.stringify(form) }); toast(editing ? "角色权限已更新" : "角色已创建"); setOpen(false); await Promise.all([reload(), refreshLookups()]); } catch (reason) { toast(reason instanceof Error ? reason.message : "保存失败", "error"); } finally { setSaving(false); } }
  async function remove(item: Role) { if (!confirm(`确定停用角色“${item.name}”吗？`)) return; try { await apiFetch(`/api/roles/${item.id}`, { method: "DELETE" }); toast("角色已停用"); await Promise.all([reload(), refreshLookups()]); } catch (reason) { toast(reason instanceof Error ? reason.message : "停用失败", "error"); } }
  if (loading) return <LoadingState />; if (error || !data) return <ErrorState message={error || "无法加载角色"} retry={reload} />;
  return <><PageHeader eyebrow="管理员自由配置" title="角色与权限" description="先为角色勾选操作权限，再把账号分配到对应角色。" actions={can("roles:manage") && <button className="button button-primary" onClick={() => show()}><Plus size={17} />创建角色</button>} />
    <section className="role-grid">{data.rows.map((role) => <article className={`panel role-card ${role.isSystem ? "system-role" : ""}`} key={role.id}><div className="role-card-head"><span className="role-icon"><ShieldCheck size={21} /></span><div><h2>{role.name}</h2><p>{role.description || "暂无说明"}</p></div>{role.isSystem && <span className="soft-badge success">系统角色</span>}</div><div className="role-stats"><span><UsersRound size={16} />{role.userCount} 个账号</span><span>{role.dataScope === "all" ? "查看全部数据" : "本部门数据"}</span></div><div className="permission-preview">{role.permissions.includes("*") ? <span>拥有全部系统权限</span> : <>{role.permissions.slice(0, 5).map((key) => <span key={key}>{data.permissionGroups.flatMap((g) => g.items).find((item) => item.key === key)?.label || key}</span>)}{role.permissions.length > 5 && <span>+{role.permissions.length - 5}</span>}</>}</div>{can("roles:manage") && !role.isSystem && <div className="role-actions"><button className="button button-secondary button-compact" onClick={() => show(role)}><Edit3 size={15} />编辑权限</button><button className="icon-button danger" onClick={() => remove(role)}><Trash2 size={16} /></button></div>}</article>)}</section>
    {open && <Modal title={editing ? `编辑角色 ${editing.name}` : "创建角色"} onClose={() => setOpen(false)} wide><form className="modal-form role-form" onSubmit={submit}><div className="form-grid"><Field label="角色名称" required><input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></Field><Field label="数据查看范围" required><select value={form.dataScope} onChange={(event) => setForm({ ...form, dataScope: event.target.value as "all" | "department" })}><option value="department">仅所属部门相关数据</option><option value="all">全公司全部数据</option></select></Field><Field label="角色说明" className="field-full"><input value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></Field></div><div className="permission-matrix"><header><div><b>功能权限</b><p>勾选这个角色可以执行的操作</p></div><span>已选择 {form.permissions.length} 项</span></header>{data.permissionGroups.map((group) => { const keys = group.items.map((item) => item.key); return <section key={group.label}><div className="permission-group-title"><label><input type="checkbox" checked={keys.every((key) => form.permissions.includes(key))} onChange={() => toggleGroup(keys)} /><b>{group.label}</b></label></div><div className="permission-items">{group.items.map((item) => <label className={form.permissions.includes(item.key) ? "checked" : ""} key={item.key}><input type="checkbox" checked={form.permissions.includes(item.key)} onChange={() => toggle(item.key)} /><span>{item.label}</span></label>)}</div></section>; })}</div><div className="modal-actions"><button type="button" className="button button-ghost" onClick={() => setOpen(false)}>取消</button><button className="button button-primary" disabled={saving}>{saving ? "保存中…" : "保存角色"}</button></div></form></Modal>}
  </>;
}
