"use client";

import { FormEvent, useState } from "react";
import { Building2, Edit3, MapPin, Plus, Tags, Trash2 } from "lucide-react";
import { DEPARTMENT_KINDS } from "@/lib/constants";
import { apiFetch, useAppData, useRemote, useToast } from "../client-utils";
import { EmptyState, ErrorState, Field, LoadingState, Modal, PageHeader } from "../ui";

type Department = { id: string; name: string; kind: string; description?: string; userCount: number; sampleCount: number };
type Location = { id: string; departmentId: string; departmentName: string; name: string; code?: string; description?: string; sampleCount: number };
type CatalogData = { categories: Array<{ id: string; name: string }>; tags: Array<{ id: string; name: string; color: string }> };

export function OrganizationView({ section }: { section: string }) {
  if (section === "departments") return <Departments />;
  if (section === "locations") return <Locations />;
  return <Catalog />;
}

function Departments() {
  const { can, refreshLookups } = useAppData(); const toast = useToast(); const { data, loading, error, reload } = useRemote<Department[]>("/api/departments"); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<Department | null>(null); const [form, setForm] = useState({ name: "", kind: "live_room", description: "" }); const [saving, setSaving] = useState(false);
  function show(item?: Department) { setEditing(item || null); setForm(item ? { name: item.name, kind: item.kind, description: item.description || "" } : { name: "", kind: "live_room", description: "" }); setOpen(true); }
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); try { await apiFetch(editing ? `/api/departments/${editing.id}` : "/api/departments", { method: editing ? "PATCH" : "POST", body: JSON.stringify(form) }); toast(editing ? "部门已修改" : "部门已创建"); setOpen(false); await Promise.all([reload(), refreshLookups()]); } catch (reason) { toast(reason instanceof Error ? reason.message : "保存失败", "error"); } finally { setSaving(false); } }
  async function remove(item: Department) { if (!confirm(`确定删除部门“${item.name}”吗？`)) return; try { await apiFetch(`/api/departments/${item.id}`, { method: "DELETE" }); toast("部门已停用"); await Promise.all([reload(), refreshLookups()]); } catch (reason) { toast(reason instanceof Error ? reason.message : "删除失败", "error"); } }
  return <><PageHeader eyebrow="平级组织结构" title="部门与直播间" description="商务部、各直播间和其他部门在这里统一维护。" actions={can("departments:manage") && <button className="button button-primary" onClick={() => show()}><Plus size={17} />新建部门</button>} />
    {loading ? <LoadingState /> : error ? <ErrorState message={error} retry={reload} /> : <section className="organization-grid">{data?.map((item) => <article className="panel organization-card" key={item.id}><div className={`organization-icon kind-${item.kind}`}><Building2 size={22} /></div><div className="organization-copy"><span>{DEPARTMENT_KINDS.find((kind) => kind.value === item.kind)?.label}</span><h2>{item.name}</h2><p>{item.description || "暂无说明"}</p><div><b>{item.userCount}</b><small>账号</small><b>{item.sampleCount}</b><small>件样品</small></div></div>{can("departments:manage") && <div className="card-menu"><button className="icon-button" onClick={() => show(item)} title="编辑"><Edit3 size={17} /></button><button className="icon-button danger" onClick={() => remove(item)} title="删除"><Trash2 size={17} /></button></div>}</article>)}{!data?.length && <EmptyState title="暂无部门" />}</section>}
    {open && <Modal title={editing ? "编辑部门" : "新建部门"} onClose={() => setOpen(false)}><form className="modal-form" onSubmit={submit}><Field label="部门名称" required><input autoFocus value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} placeholder="例如：小雪直播间" /></Field><Field label="部门类型" required><select value={form.kind} onChange={(event) => setForm({ ...form, kind: event.target.value })}>{DEPARTMENT_KINDS.map((item) => <option value={item.value} key={item.value}>{item.label}</option>)}</select></Field><Field label="说明"><textarea rows={3} value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></Field><div className="modal-actions"><button type="button" className="button button-ghost" onClick={() => setOpen(false)}>取消</button><button className="button button-primary" disabled={saving}>{saving ? "保存中…" : "保存"}</button></div></form></Modal>}
  </>;
}

function Locations() {
  const { lookups, can, refreshLookups } = useAppData(); const toast = useToast(); const { data, loading, error, reload } = useRemote<Location[]>("/api/locations"); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<Location | null>(null); const [form, setForm] = useState({ departmentId: "", name: "", code: "", description: "" }); const [saving, setSaving] = useState(false);
  function show(item?: Location) { setEditing(item || null); setForm(item ? { departmentId: item.departmentId, name: item.name, code: item.code || "", description: item.description || "" } : { departmentId: lookups?.departments.find((d) => d.kind === "business")?.id || lookups?.departments[0]?.id || "", name: "", code: "", description: "" }); setOpen(true); }
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); try { await apiFetch(editing ? `/api/locations/${editing.id}` : "/api/locations", { method: editing ? "PATCH" : "POST", body: JSON.stringify(form) }); toast(editing ? "位置已修改" : "位置已创建"); setOpen(false); await Promise.all([reload(), refreshLookups()]); } catch (reason) { toast(reason instanceof Error ? reason.message : "保存失败", "error"); } finally { setSaving(false); } }
  async function remove(item: Location) { if (!confirm(`确定删除位置“${item.name}”吗？`)) return; try { await apiFetch(`/api/locations/${item.id}`, { method: "DELETE" }); toast("位置已停用"); await Promise.all([reload(), refreshLookups()]); } catch (reason) { toast(reason instanceof Error ? reason.message : "删除失败", "error"); } }
  const grouped = (data || []).reduce<Record<string, Location[]>>((acc, item) => { (acc[item.departmentName] ||= []).push(item); return acc; }, {});
  return <><PageHeader eyebrow="精确到货架或区域" title="具体存放位置" description="尤其适合维护商务部仓库、货架、房间或样品区。" actions={can("locations:manage") && <button className="button button-primary" onClick={() => show()}><Plus size={17} />新增位置</button>} />
    {loading ? <LoadingState /> : error ? <ErrorState message={error} retry={reload} /> : !data?.length ? <EmptyState title="暂无具体位置" description="可先为商务部创建货架或存放区域。" /> : <div className="location-groups">{Object.entries(grouped).map(([department, items]) => <section className="panel" key={department}><header className="panel-header padded"><div><p className="eyebrow">所属部门</p><h2>{department}</h2></div><span className="soft-badge">{items.length} 个位置</span></header><div className="location-card-grid">{items.map((item) => <article className="location-card" key={item.id}><div className="location-pin"><MapPin size={19} /></div><div><h3>{item.name}</h3><p>{item.code ? `位置编码 ${item.code}` : item.description || "暂无说明"}</p><span>{item.sampleCount} 件样品</span></div>{can("locations:manage") && <div className="card-menu"><button className="icon-button" onClick={() => show(item)}><Edit3 size={16} /></button><button className="icon-button danger" onClick={() => remove(item)}><Trash2 size={16} /></button></div>}</article>)}</div></section>)}</div>}
    {open && <Modal title={editing ? "编辑存放位置" : "新增存放位置"} onClose={() => setOpen(false)}><form className="modal-form" onSubmit={submit}><Field label="所属部门" required><select value={form.departmentId} onChange={(event) => setForm({ ...form, departmentId: event.target.value })}><option value="">请选择</option>{lookups?.departments.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></Field><Field label="位置名称" required><input autoFocus value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} placeholder="例如：A 区 2 号货架" /></Field><Field label="位置编码"><input value={form.code} onChange={(event) => setForm({ ...form, code: event.target.value })} placeholder="例如 A-02" /></Field><Field label="说明"><textarea rows={3} value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></Field><div className="modal-actions"><button type="button" className="button button-ghost" onClick={() => setOpen(false)}>取消</button><button className="button button-primary" disabled={saving}>保存</button></div></form></Modal>}
  </>;
}

function Catalog() {
  const { can, refreshLookups } = useAppData(); const toast = useToast(); const { data, loading, error, reload } = useRemote<CatalogData>("/api/catalog"); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<{ id: string; type: "category" | "tag"; name: string; color?: string } | null>(null); const [form, setForm] = useState({ type: "category" as "category" | "tag", name: "", color: "#56736a" });
  function show(type: "category" | "tag", item?: { id: string; name: string; color?: string }) { setEditing(item ? { ...item, type } : null); setForm({ type, name: item?.name || "", color: item?.color || "#56736a" }); setOpen(true); }
  async function submit(event: FormEvent) { event.preventDefault(); try { await apiFetch(editing ? `/api/catalog/${editing.id}` : "/api/catalog", { method: editing ? "PATCH" : "POST", body: JSON.stringify(form) }); toast("已保存"); setOpen(false); await Promise.all([reload(), refreshLookups()]); } catch (reason) { toast(reason instanceof Error ? reason.message : "保存失败", "error"); } }
  async function remove(type: "category" | "tag", item: { id: string; name: string }) { if (!confirm(`确定停用“${item.name}”吗？`)) return; try { await apiFetch(`/api/catalog/${item.id}?type=${type}`, { method: "DELETE" }); toast("已停用"); await Promise.all([reload(), refreshLookups()]); } catch (reason) { toast(reason instanceof Error ? reason.message : "操作失败", "error"); } }
  if (loading) return <LoadingState />; if (error) return <ErrorState message={error} retry={reload} />;
  return <><PageHeader eyebrow="方便筛选与统计" title="商品分类与标签" description="分类用于商品归类，标签用于标记重点推广、高佣金等特征。" />
    <div className="catalog-grid"><section className="panel catalog-panel"><header className="panel-header padded"><div><p className="eyebrow">单一分类</p><h2>商品分类</h2></div>{can("catalog:manage") && <button className="button button-secondary button-compact" onClick={() => show("category")}><Plus size={16} />新建</button>}</header><div className="catalog-list">{data?.categories.map((item) => <div key={item.id}><span className="catalog-icon"><Tags size={17} /></span><b>{item.name}</b>{can("catalog:manage") && <div><button className="icon-button" onClick={() => show("category", item)}><Edit3 size={15} /></button><button className="icon-button danger" onClick={() => remove("category", item)}><Trash2 size={15} /></button></div>}</div>)}</div></section><section className="panel catalog-panel"><header className="panel-header padded"><div><p className="eyebrow">可多选</p><h2>商品标签</h2></div>{can("catalog:manage") && <button className="button button-secondary button-compact" onClick={() => show("tag")}><Plus size={16} />新建</button>}</header><div className="catalog-list tag-list">{data?.tags.map((item) => <div key={item.id}><i style={{ background: item.color }} /><b>{item.name}</b>{can("catalog:manage") && <div><button className="icon-button" onClick={() => show("tag", item)}><Edit3 size={15} /></button><button className="icon-button danger" onClick={() => remove("tag", item)}><Trash2 size={15} /></button></div>}</div>)}</div></section></div>
    {open && <Modal title={editing ? "编辑" : form.type === "category" ? "新建分类" : "新建标签"} onClose={() => setOpen(false)}><form className="modal-form" onSubmit={submit}><Field label="名称" required><input autoFocus value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></Field>{form.type === "tag" && <Field label="标签颜色"><input type="color" value={form.color} onChange={(event) => setForm({ ...form, color: event.target.value })} /></Field>}<div className="modal-actions"><button type="button" className="button button-ghost" onClick={() => setOpen(false)}>取消</button><button className="button button-primary">保存</button></div></form></Modal>}
  </>;
}
