"use client";
/* eslint-disable @next/next/no-img-element -- 商品预览直接使用外部图片网址，不经过服务器图片代理。 */

import Link from "next/link";
import { useRouter } from "next/navigation";
import { FormEvent, useEffect, useState } from "react";
import { Archive, ArrowLeft, Boxes, CalendarDays, Download, ExternalLink, FilePenLine, Filter, ImagePlus, MapPin, PackagePlus, Plus, Search, Store, UserRound } from "lucide-react";
import { activeLocationLabel } from "@/lib/constants";
import { apiFetch, formatDate, useAppData, useRemote, useToast } from "../client-utils";
import { EmptyState, ErrorState, Field, LoadingState, Modal, PageHeader, Pagination, ProductImage, StatusBadge } from "../ui";

type ProductRow = { id: string; sku: string; name: string; storeName?: string; price?: string; productUrl?: string; commission?: string; storeRating?: string; supplyChain?: string; imageUrls: string[]; createdAt: string; updatedAt?: string; categoryName?: string; businessContactName?: string; sampleCount: number; activeCount: number; selectedDepartments?: string; tags?: string };
type ProductListData = { rows: ProductRow[]; total: number; page: number; pageSize: number };
type SampleRow = { id: string; code: string; arrivedAt: string; status: string; note?: string; departmentName?: string; locationName?: string; updatedAt: string };
type ProductDetailData = { product: ProductRow & { businessContactId?: string; cooperationMechanism?: string; categoryId?: string; notes?: string; departments: Array<{ id: string; name: string }>; tags: Array<{ id: string; name: string; color: string }> }; samples: SampleRow[] };

export function ProductsView() {
  const { lookups, can } = useAppData(); const [search, setSearch] = useState(""); const [departmentId, setDepartmentId] = useState(""); const [categoryId, setCategoryId] = useState(""); const [page, setPage] = useState(1);
  const query = new URLSearchParams({ search, departmentId, categoryId, page: String(page) }).toString();
  const { data, loading, error, reload } = useRemote<ProductListData>(`/api/products?${query}`);
  return <>
    <PageHeader eyebrow="商品档案" title="所有商品款式" description="一个货号对应一个款式，同款的每件实物都拥有独立编号。" actions={<>{can("products:export") && <Link className="button button-secondary" href="/api/export?type=products"><Download size={17} />导出 Excel</Link>}{can("products:create") && <Link className="button button-primary" href="/products/new"><PackagePlus size={18} />登记新商品</Link>}</>} />
    <section className="toolbar"><div className="search-box"><Search size={18} /><input value={search} onChange={(event) => { setSearch(event.target.value); setPage(1); }} placeholder="搜索货号、商品名、店铺名" /></div><div className="toolbar-filters"><div className="select-wrap"><Filter size={16} /><select value={departmentId} onChange={(event) => { setDepartmentId(event.target.value); setPage(1); }}><option value="">全部选品直播间</option>{lookups?.departments.filter((item) => item.kind === "live_room").map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></div><select value={categoryId} onChange={(event) => { setCategoryId(event.target.value); setPage(1); }}><option value="">全部分类</option>{lookups?.categories.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></div></section>
    <section className="panel table-panel">
      {loading ? <LoadingState /> : error ? <ErrorState message={error} retry={reload} /> : !data?.rows.length ? <EmptyState title="没有找到商品" description={search ? "试试更换搜索条件。" : "登记第一款商品后会显示在这里。"} action={can("products:create") ? <Link href="/products/new" className="button button-primary">登记商品</Link> : undefined} /> : <><div className="data-table-wrap"><table className="data-table product-table"><thead><tr><th>商品</th><th>选品直播间</th><th>商务信息</th><th>实物数量</th><th>最近更新</th><th /></tr></thead><tbody>{data.rows.map((product) => <tr key={product.id}><td><Link href={`/products/${product.id}`} className="table-product"><ProductImage urls={product.imageUrls} alt={product.name} size="small" /><div><b>{product.name}</b><span>{product.sku} {product.categoryName && `· ${product.categoryName}`}</span>{product.tags && <small>{product.tags}</small>}</div></Link></td><td><span className="table-place"><MapPin size={15} />{product.selectedDepartments || "—"}</span></td><td><div className="stacked-cell"><span>{product.storeName || "未填店铺"}</span><small>{product.businessContactName || "未指定对接人"}{product.commission ? ` · 佣金 ${product.commission}` : ""}</small></div></td><td><b className="quantity-number">{product.sampleCount}</b><small className="quantity-sub">{product.activeCount} 件在库/在用</small></td><td>{formatDate(product.updatedAt || product.createdAt)}</td><td><Link className="row-link" href={`/products/${product.id}`}>查看</Link></td></tr>)}</tbody></table></div><div className="mobile-record-list">{data.rows.map((product) => <Link href={`/products/${product.id}`} className="mobile-record" key={product.id}><ProductImage urls={product.imageUrls} alt={product.name} size="medium" /><div className="mobile-record-main"><div><span className="sku-chip">{product.sku}</span><b>{product.name}</b></div><p><MapPin size={14} />{product.selectedDepartments || "未指定直播间"}</p><small>{product.sampleCount} 件样品 · {formatDate(product.updatedAt)}</small></div></Link>)}</div><Pagination page={data.page} pageSize={data.pageSize} total={data.total} onChange={setPage} /></>}
    </section>
  </>;
}

type ProductFormState = { sku: string; name: string; departmentIds: string[]; businessContactId: string; storeName: string; price: string; productUrl: string; commission: string; storeRating: string; supplyChain: string; cooperationMechanism: string; categoryId: string; tagIds: string[]; imageUrls: string; notes: string; quantity: string; arrivedAt: string; initialDepartmentId: string; initialLocationId: string };
const today = () => { const date = new Date(); date.setMinutes(date.getMinutes() - date.getTimezoneOffset()); return date.toISOString().slice(0, 10); };
const blankForm = (): ProductFormState => ({ sku: "", name: "", departmentIds: [], businessContactId: "", storeName: "", price: "", productUrl: "", commission: "", storeRating: "", supplyChain: "", cooperationMechanism: "", categoryId: "", tagIds: [], imageUrls: "", notes: "", quantity: "1", arrivedAt: today(), initialDepartmentId: "", initialLocationId: "" });

export function ProductFormView({ id }: { id?: string }) {
  const { lookups } = useAppData(); const router = useRouter(); const toast = useToast(); const [form, setForm] = useState<ProductFormState>(blankForm); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const detail = useRemote<ProductDetailData>(id ? `/api/products/${id}` : null);
  useEffect(() => { if (!id && lookups && !form.initialDepartmentId) { const business = lookups.departments.find((item) => item.kind === "business"); if (business) setForm((current) => ({ ...current, initialDepartmentId: business.id })); } }, [id, lookups, form.initialDepartmentId]);
  useEffect(() => { if (id && detail.data) { const p = detail.data.product; setForm({ sku: p.sku, name: p.name, departmentIds: p.departments.map((item) => item.id), businessContactId: p.businessContactId || "", storeName: p.storeName || "", price: p.price || "", productUrl: p.productUrl || "", commission: p.commission || "", storeRating: p.storeRating || "", supplyChain: p.supplyChain || "", cooperationMechanism: p.cooperationMechanism || "", categoryId: p.categoryId || "", tagIds: p.tags.map((item) => item.id), imageUrls: (p.imageUrls || []).join("\n"), notes: p.notes || "", quantity: "1", arrivedAt: today(), initialDepartmentId: "", initialLocationId: "" }); } }, [id, detail.data]);
  const set = (key: keyof ProductFormState, value: string | string[]) => setForm((current) => ({ ...current, [key]: value }));
  const imageUrls = form.imageUrls.split(/\r?\n/).map((value) => value.trim()).filter(Boolean);
  const locations = lookups?.locations.filter((item) => item.departmentId === form.initialDepartmentId) || [];
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setError(""); try { const payload = { ...form, price: form.price || null, storeRating: form.storeRating || null, businessContactId: form.businessContactId || null, categoryId: form.categoryId || null, productUrl: form.productUrl || "", imageUrls, initialLocationId: form.initialLocationId || null }; if (id) { const { quantity, arrivedAt, initialDepartmentId, initialLocationId, ...update } = payload; void quantity; void arrivedAt; void initialDepartmentId; void initialLocationId; await apiFetch(`/api/products/${id}`, { method: "PATCH", body: JSON.stringify(update) }); toast("商品信息已保存"); router.push(`/products/${id}`); } else { const result = await apiFetch<{ id: string }>("/api/products", { method: "POST", body: JSON.stringify(payload) }); toast(`商品登记成功，已创建 ${form.quantity} 件实物样品`); router.push(`/products/${result.id}`); } } catch (reason) { setError(reason instanceof Error ? reason.message : "保存失败"); window.scrollTo({ top: 0, behavior: "smooth" }); } finally { setSaving(false); } }
  if (id && detail.loading) return <LoadingState />;
  return <form onSubmit={submit}>
    <PageHeader eyebrow={id ? "编辑档案" : "到样登记"} title={id ? "修改商品信息" : "登记新商品与实物样品"} description={id ? "商品链接等字段的每次修改都会保留操作记录。" : "先建立款式档案，系统会按到样数量自动创建独立实物编号。"} actions={<><button type="button" className="button button-ghost" onClick={() => router.back()}><ArrowLeft size={17} />返回</button><button className="button button-primary" disabled={saving}>{saving ? "正在保存…" : id ? "保存修改" : "完成登记"}</button></>} />
    {error && <div className="form-error page-form-error">{error}</div>}
    <div className="form-layout"><div className="form-main">
      <section className="panel form-section"><header><span className="section-number">01</span><div><h2>商品基本信息</h2><p>货号对应唯一款式，不同颜色或规格请使用新货号。</p></div></header><div className="form-grid">
        <Field label="货号" required><input value={form.sku} onChange={(event) => set("sku", event.target.value)} placeholder="例如 SY-2026-001" /></Field><Field label="商品名称" required><input value={form.name} onChange={(event) => set("name", event.target.value)} placeholder="输入便于查找的商品名称" /></Field>
        <Field label="商品分类"><select value={form.categoryId} onChange={(event) => set("categoryId", event.target.value)}><option value="">暂不分类</option>{lookups?.categories.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></Field><Field label="商务对接人"><select value={form.businessContactId} onChange={(event) => set("businessContactId", event.target.value)}><option value="">暂不指定</option>{lookups?.users.map((item) => <option value={item.id} key={item.id}>{item.name} · {item.departmentName}</option>)}</select></Field>
        <Field label="选品直播间" required className="field-full"><div className="check-grid">{lookups?.departments.filter((item) => item.kind === "live_room").map((item) => <label className={`check-card ${form.departmentIds.includes(item.id) ? "checked" : ""}`} key={item.id}><input type="checkbox" checked={form.departmentIds.includes(item.id)} onChange={() => set("departmentIds", form.departmentIds.includes(item.id) ? form.departmentIds.filter((value) => value !== item.id) : [...form.departmentIds, item.id])} /><span>{item.name}</span></label>)}{lookups && !lookups.departments.some((item) => item.kind === "live_room") && <p className="inline-hint">请先在“部门管理”中创建直播间部门。</p>}</div></Field>
        <Field label="商品标签" className="field-full"><div className="tag-picker">{lookups?.tags.map((item) => <label key={item.id} style={{ "--tag-color": item.color } as React.CSSProperties} className={form.tagIds.includes(item.id) ? "selected" : ""}><input type="checkbox" checked={form.tagIds.includes(item.id)} onChange={() => set("tagIds", form.tagIds.includes(item.id) ? form.tagIds.filter((value) => value !== item.id) : [...form.tagIds, item.id])} />{item.name}</label>)}</div></Field>
      </div></section>
      <section className="panel form-section"><header><span className="section-number">02</span><div><h2>店铺与合作信息</h2><p>这些字段可后续修改，商品链接变更会记录操作人和时间。</p></div></header><div className="form-grid">
        <Field label="店铺名"><input value={form.storeName} onChange={(event) => set("storeName", event.target.value)} /></Field><Field label="供应链 / 机构"><input value={form.supplyChain} onChange={(event) => set("supplyChain", event.target.value)} /></Field>
        <Field label="价格"><div className="input-suffix"><input type="number" min="0" step="0.01" value={form.price} onChange={(event) => set("price", event.target.value)} /><span>元</span></div></Field><Field label="佣金"><input value={form.commission} onChange={(event) => set("commission", event.target.value)} placeholder="例如 20%" /></Field>
        <Field label="店铺评分"><input type="number" min="0" max="5" step="0.01" value={form.storeRating} onChange={(event) => set("storeRating", event.target.value)} placeholder="0 - 5" /></Field><Field label="合作机制"><input value={form.cooperationMechanism} onChange={(event) => set("cooperationMechanism", event.target.value)} placeholder="填写合作、佣金或排期说明" /></Field>
        <Field label="商品链接" className="field-full"><div className="input-prefix"><ExternalLink size={17} /><input type="url" value={form.productUrl} onChange={(event) => set("productUrl", event.target.value)} placeholder="https://..." /></div></Field>
      </div></section>
      <section className="panel form-section"><header><span className="section-number">03</span><div><h2>外部商品图片</h2><p>系统只保存图片网址，不上传图片文件，不占用服务器图片容量。</p></div></header><div className="image-url-layout"><Field label="图片网址" hint="每行填写一个完整图片网址，最多 12 张。"><textarea rows={6} value={form.imageUrls} onChange={(event) => set("imageUrls", event.target.value)} placeholder={"https://example.com/image-1.jpg\nhttps://example.com/image-2.jpg"} /></Field><div className="image-preview-grid">{imageUrls.length ? imageUrls.slice(0, 6).map((url, index) => <div className="image-preview" key={`${url}-${index}`}><img src={url} alt={`预览 ${index + 1}`} referrerPolicy="no-referrer" /></div>) : <div className="image-preview-empty"><ImagePlus size={26} /><span>图片预览</span></div>}</div></div></section>
    </div><aside className="form-side">
      {!id && <section className="panel form-section arrival-card"><header><span className="section-number">04</span><div><h2>本次到样</h2><p>每件实物会获得独立编号。</p></div></header><div className="form-grid single">
        <Field label="到样数量" required><div className="input-suffix"><input type="number" min="1" max="500" value={form.quantity} onChange={(event) => set("quantity", event.target.value)} /><span>件</span></div></Field><Field label="到样日期" required><input type="date" value={form.arrivedAt} onChange={(event) => set("arrivedAt", event.target.value)} /></Field>
        <Field label="初始所在部门" required><select value={form.initialDepartmentId} onChange={(event) => { set("initialDepartmentId", event.target.value); set("initialLocationId", ""); }}><option value="">请选择部门</option>{lookups?.departments.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></Field><Field label="具体存放位置"><select value={form.initialLocationId} onChange={(event) => set("initialLocationId", event.target.value)}><option value="">暂不细分</option>{locations.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></Field>
      </div><div className="arrival-result"><Boxes size={20} /><div><b>将创建 {Number(form.quantity) || 0} 个独立编号</b><span>例如 SY-{form.arrivedAt.replaceAll("-", "") || "日期"}-000001</span></div></div></section>}
      <section className="panel form-section"><header><div><h2>备注</h2><p>可记录选品或合作补充信息。</p></div></header><Field label="内部备注"><textarea rows={6} value={form.notes} onChange={(event) => set("notes", event.target.value)} /></Field></section>
    </aside></div>
  </form>;
}

export function ProductDetailView({ id }: { id: string }) {
  const { can, lookups } = useAppData(); const router = useRouter(); const toast = useToast(); const { data, loading, error, reload } = useRemote<ProductDetailData>(`/api/products/${id}`); const [stockOpen, setStockOpen] = useState(false);
  const [stock, setStock] = useState({ quantity: "1", arrivedAt: today(), departmentId: "", locationId: "", note: "" }); const [saving, setSaving] = useState(false);
  useEffect(() => { if (lookups && !stock.departmentId) { const business = lookups.departments.find((item) => item.kind === "business"); if (business) setStock((value) => ({ ...value, departmentId: business.id })); } }, [lookups, stock.departmentId]);
  if (loading) return <LoadingState />; if (error || !data) return <ErrorState message={error || "商品不存在"} retry={reload} />;
  const p = data.product; const stockLocations = lookups?.locations.filter((item) => item.departmentId === stock.departmentId) || [];
  async function addStock(event: FormEvent) { event.preventDefault(); setSaving(true); try { await apiFetch(`/api/products/${id}/stock`, { method: "POST", body: JSON.stringify({ ...stock, locationId: stock.locationId || null }) }); toast(`已追加 ${stock.quantity} 件实物样品`); setStockOpen(false); await reload(); } catch (reason) { toast(reason instanceof Error ? reason.message : "追加失败", "error"); } finally { setSaving(false); } }
  async function archive() { if (!confirm("确定归档这个商品吗？在用样品未处理时不能归档。")) return; try { await apiFetch(`/api/products/${id}`, { method: "DELETE" }); toast("商品已归档"); router.push("/products"); } catch (reason) { toast(reason instanceof Error ? reason.message : "归档失败", "error"); } }
  return <>
    <PageHeader eyebrow={p.sku} title={p.name} description={`${p.departments.map((item) => item.name).join("、")} · 共 ${data.samples.length} 件实物样品`} actions={<><Link href="/products" className="button button-ghost"><ArrowLeft size={17} />返回</Link>{can("products:edit") && <button className="button button-secondary" onClick={() => setStockOpen(true)}><Plus size={17} />追加到样</button>}{can("products:edit") && <Link href={`/products/${id}/edit`} className="button button-primary"><FilePenLine size={17} />编辑档案</Link>}</>} />
    <div className="detail-grid"><section className="panel product-hero-card"><ProductImage urls={p.imageUrls} alt={p.name} size="large" /><div className="product-hero-copy"><div className="badge-line"><span className="sku-chip">{p.sku}</span>{p.categoryName && <span className="soft-badge">{p.categoryName}</span>}{p.tags.map((tag) => <span className="soft-badge" style={{ borderColor: tag.color, color: tag.color }} key={tag.id}>{tag.name}</span>)}</div><h2>{p.name}</h2><div className="product-meta-grid"><span><Store size={16} />{p.storeName || "未填店铺"}</span><span><UserRound size={16} />{p.businessContactName || "未指定商务"}</span><span><MapPin size={16} />{p.departments.map((item) => item.name).join("、")}</span><span><CalendarDays size={16} />登记于 {formatDate(p.createdAt)}</span></div><div className="commercial-line"><div><small>价格</small><b>{p.price ? `¥${p.price}` : "—"}</b></div><div><small>佣金</small><b>{p.commission || "—"}</b></div><div><small>店铺评分</small><b>{p.storeRating || "—"}</b></div></div>{p.productUrl && <a className="external-product-link" href={p.productUrl} target="_blank" rel="noreferrer"><ExternalLink size={16} />打开商品链接</a>}</div></section>
      <section className="panel detail-info"><h2>合作信息</h2><dl><div><dt>供应链 / 机构</dt><dd>{p.supplyChain || "—"}</dd></div><div><dt>合作机制</dt><dd>{p.cooperationMechanism || "—"}</dd></div><div><dt>内部备注</dt><dd>{p.notes || "—"}</dd></div></dl>{can("products:archive") && <button className="danger-link" onClick={archive}><Archive size={16} />归档商品</button>}</section></div>
    <section className="panel table-panel"><header className="panel-header padded"><div><p className="eyebrow">逐件管理</p><h2>实物样品（{data.samples.length}）</h2></div></header>{data.samples.length === 0 ? <EmptyState title="暂时没有实物样品" /> : <><div className="data-table-wrap"><table className="data-table"><thead><tr><th>独立编号</th><th>到样日期</th><th>状态</th><th>当前位置</th><th>最后更新</th><th /></tr></thead><tbody>{data.samples.map((sample) => <tr key={sample.id}><td><Link href={`/samples/${sample.code}`} className="code-link">{sample.code}</Link></td><td>{formatDate(sample.arrivedAt)}</td><td><StatusBadge status={sample.status} /></td><td>{activeLocationLabel({ status: sample.status, department_name: sample.departmentName, location_name: sample.locationName })}</td><td>{formatDate(sample.updatedAt, true)}</td><td><Link className="row-link" href={`/samples/${sample.code}`}>查看流转</Link></td></tr>)}</tbody></table></div><div className="mobile-record-list">{data.samples.map((sample) => <Link href={`/samples/${sample.code}`} className="mobile-record compact" key={sample.id}><div><b className="code-link">{sample.code}</b><p>{activeLocationLabel({ status: sample.status, department_name: sample.departmentName, location_name: sample.locationName })}</p><small>到样 {formatDate(sample.arrivedAt)}</small></div><StatusBadge status={sample.status} /></Link>)}</div></> }</section>
    {stockOpen && <Modal title="追加实物样品" onClose={() => setStockOpen(false)}><form className="modal-form" onSubmit={addStock}><div className="form-grid"><Field label="追加数量" required><input type="number" min="1" max="500" value={stock.quantity} onChange={(event) => setStock({ ...stock, quantity: event.target.value })} /></Field><Field label="到样日期" required><input type="date" value={stock.arrivedAt} onChange={(event) => setStock({ ...stock, arrivedAt: event.target.value })} /></Field><Field label="所在部门" required><select value={stock.departmentId} onChange={(event) => setStock({ ...stock, departmentId: event.target.value, locationId: "" })}><option value="">请选择</option>{lookups?.departments.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></Field><Field label="具体位置"><select value={stock.locationId} onChange={(event) => setStock({ ...stock, locationId: event.target.value })}><option value="">暂不细分</option>{stockLocations.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></Field><Field label="备注" className="field-full"><textarea rows={3} value={stock.note} onChange={(event) => setStock({ ...stock, note: event.target.value })} /></Field></div><div className="modal-actions"><button type="button" className="button button-ghost" onClick={() => setStockOpen(false)}>取消</button><button className="button button-primary" disabled={saving}>{saving ? "正在创建…" : `创建 ${stock.quantity || 0} 件样品`}</button></div></form></Modal>}
  </>;
}
