"use client";
/* eslint-disable @next/next/no-img-element -- 二维码是即时生成的数据网址，不能交给 Next 图片代理。 */

import Link from "next/link";
import { useRouter } from "next/navigation";
import { FormEvent, useEffect, useRef, useState } from "react";
import { Archive, ArrowLeft, Camera, Check, Clipboard, Download, History, Keyboard, MapPin, MoveRight, QrCode, ScanLine, Search, Smartphone, X } from "lucide-react";
import { activeLocationLabel, SAMPLE_STATUSES, statusLabel } from "@/lib/constants";
import { apiFetch, formatDate, useAppData, useRemote, useToast } from "../client-utils";
import { EmptyState, ErrorState, Field, LoadingState, Modal, PageHeader, Pagination, ProductImage, StatusBadge } from "../ui";

type SampleRow = { id: string; code: string; arrivedAt: string; status: string; note?: string; updatedAt: string; productId: string; sku: string; productName: string; imageUrls: string[]; departmentId?: string; departmentName?: string; locationId?: string; locationName?: string };
type ListData = { rows: SampleRow[]; total: number; page: number; pageSize: number };

export function SamplesView() {
  const { lookups, can } = useAppData(); const toast = useToast(); const [search, setSearch] = useState(""); const [status, setStatus] = useState(""); const [departmentId, setDepartmentId] = useState(""); const [locationId, setLocationId] = useState(""); const [page, setPage] = useState(1); const [selected, setSelected] = useState<string[]>([]); const [batchOpen, setBatchOpen] = useState(false);
  const query = new URLSearchParams({ search, status, departmentId, locationId, page: String(page) }).toString(); const { data, loading, error, reload } = useRemote<ListData>(`/api/samples?${query}`);
  const [batch, setBatch] = useState({ status: "active", departmentId: "", locationId: "", remark: "" }); const [saving, setSaving] = useState(false);
  const filteredLocations = lookups?.locations.filter((item) => !departmentId || item.departmentId === departmentId) || [];
  const batchLocations = lookups?.locations.filter((item) => item.departmentId === batch.departmentId) || [];
  function toggleAll() { if (!data) return; const ids = data.rows.map((item) => item.id); setSelected(ids.every((id) => selected.includes(id)) ? selected.filter((id) => !ids.includes(id)) : Array.from(new Set([...selected, ...ids]))); }
  async function submitBatch(event: FormEvent) { event.preventDefault(); setSaving(true); try { await apiFetch("/api/samples/batch", { method: "POST", body: JSON.stringify({ sampleIds: selected, ...batch, departmentId: batch.status === "active" ? batch.departmentId || null : null, locationId: batch.status === "active" ? batch.locationId || null : null }) }); toast(`已批量更新 ${selected.length} 件样品`); setBatchOpen(false); setSelected([]); await reload(); } catch (reason) { toast(reason instanceof Error ? reason.message : "更新失败", "error"); } finally { setSaving(false); } }
  return <>
    <PageHeader eyebrow="实物追踪" title="每一件样品的当前位置" description="可按独立编号、货号、商品或位置查找，并批量更新多件样品。" actions={<>{can("samples:export") && <Link className="button button-secondary" href="/api/export?type=samples"><Download size={17} />导出 Excel</Link>}<Link className="button button-primary" href="/scan"><ScanLine size={18} />扫码查样品</Link></>} />
    <section className="toolbar"><div className="search-box"><Search size={18} /><input value={search} onChange={(event) => { setSearch(event.target.value); setPage(1); }} placeholder="搜索实物编号、货号或商品名称" /></div><div className="toolbar-filters"><select value={status} onChange={(event) => { setStatus(event.target.value); setPage(1); }}><option value="">全部状态</option>{SAMPLE_STATUSES.map((item) => <option value={item.value} key={item.value}>{item.label}</option>)}</select><select value={departmentId} onChange={(event) => { setDepartmentId(event.target.value); setLocationId(""); setPage(1); }}><option value="">全部部门</option>{lookups?.departments.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select><select value={locationId} onChange={(event) => { setLocationId(event.target.value); setPage(1); }}><option value="">全部具体位置</option>{filteredLocations.map((item) => <option value={item.id} key={item.id}>{item.departmentName} · {item.name}</option>)}</select></div></section>
    {selected.length > 0 && <div className="bulk-bar"><div><span className="bulk-count">{selected.length}</span><b>件样品已选中</b><button onClick={() => setSelected([])}>取消选择</button></div>{can("samples:batch") && <button className="button button-primary" onClick={() => setBatchOpen(true)}><MoveRight size={17} />批量修改位置 / 状态</button>}</div>}
    <section className="panel table-panel">{loading ? <LoadingState /> : error ? <ErrorState message={error} retry={reload} /> : !data?.rows.length ? <EmptyState title="没有找到样品" description="可以更换筛选条件或先登记到样。" /> : <><div className="data-table-wrap"><table className="data-table samples-table"><thead><tr><th className="check-cell"><input type="checkbox" aria-label="全选" checked={data.rows.every((item) => selected.includes(item.id))} onChange={toggleAll} /></th><th>实物样品</th><th>到样日期</th><th>状态</th><th>当前位置</th><th>最后更新</th><th /></tr></thead><tbody>{data.rows.map((sample) => <tr key={sample.id} className={selected.includes(sample.id) ? "selected-row" : ""}><td className="check-cell"><input type="checkbox" checked={selected.includes(sample.id)} onChange={() => setSelected((items) => items.includes(sample.id) ? items.filter((id) => id !== sample.id) : [...items, sample.id])} aria-label={`选择 ${sample.code}`} /></td><td><Link href={`/samples/${sample.code}`} className="table-product"><ProductImage urls={sample.imageUrls} alt={sample.productName} size="small" /><div><b>{sample.productName}</b><span className="code-text">{sample.code}</span><small>货号 {sample.sku}</small></div></Link></td><td>{formatDate(sample.arrivedAt)}</td><td><StatusBadge status={sample.status} /></td><td><span className="table-place"><MapPin size={15} />{activeLocationLabel({ status: sample.status, department_name: sample.departmentName, location_name: sample.locationName })}</span></td><td>{formatDate(sample.updatedAt, true)}</td><td><Link className="row-link" href={`/samples/${sample.code}`}>详情</Link></td></tr>)}</tbody></table></div><div className="mobile-record-list">{data.rows.map((sample) => <div className={`mobile-record selectable ${selected.includes(sample.id) ? "selected" : ""}`} key={sample.id}><input type="checkbox" checked={selected.includes(sample.id)} onChange={() => setSelected((items) => items.includes(sample.id) ? items.filter((id) => id !== sample.id) : [...items, sample.id])} /><Link href={`/samples/${sample.code}`}><ProductImage urls={sample.imageUrls} alt={sample.productName} size="medium" /><div className="mobile-record-main"><div><StatusBadge status={sample.status} /><b>{sample.productName}</b></div><p><MapPin size={14} />{activeLocationLabel({ status: sample.status, department_name: sample.departmentName, location_name: sample.locationName })}</p><small>{sample.code} · 到样 {formatDate(sample.arrivedAt)}</small></div></Link></div>)}</div><Pagination page={data.page} pageSize={data.pageSize} total={data.total} onChange={setPage} /></>}</section>
    {batchOpen && <Modal title={`批量更新 ${selected.length} 件样品`} onClose={() => setBatchOpen(false)}><form className="modal-form" onSubmit={submitBatch}><Field label="更新后的状态" required><div className="status-picker compact-status-picker">{SAMPLE_STATUSES.map((item) => <label className={batch.status === item.value ? "selected" : ""} key={item.value}><input type="radio" name="batchStatus" checked={batch.status === item.value} onChange={() => setBatch({ ...batch, status: item.value, departmentId: item.value === "active" ? batch.departmentId : "", locationId: "" })} /><StatusBadge status={item.value} /></label>)}</div></Field>{batch.status === "active" && <div className="form-grid"><Field label="所在部门" required><select value={batch.departmentId} onChange={(event) => setBatch({ ...batch, departmentId: event.target.value, locationId: "" })}><option value="">请选择部门</option>{lookups?.departments.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></Field><Field label="具体位置"><select value={batch.locationId} onChange={(event) => setBatch({ ...batch, locationId: event.target.value })}><option value="">暂不细分</option>{batchLocations.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></Field></div>}<Field label="操作备注" hint="选填，例如：A 直播间使用完归还商务部。"><textarea rows={3} value={batch.remark} onChange={(event) => setBatch({ ...batch, remark: event.target.value })} /></Field><div className="modal-actions"><button type="button" className="button button-ghost" onClick={() => setBatchOpen(false)}>取消</button><button className="button button-primary" disabled={saving}>{saving ? "正在更新…" : "确认批量更新"}</button></div></form></Modal>}
  </>;
}

type SampleDetailData = { sample: SampleRow & { productId: string; storeName?: string; productUrl?: string; price?: string; commission?: string; supplyChain?: string; categoryName?: string }; movements: Array<{ id: string; fromStatus?: string; toStatus: string; remark?: string; createdAt: string; fromDepartmentName?: string; fromLocationName?: string; toDepartmentName?: string; toLocationName?: string; operatorName?: string }>; qrCode: string };

export function SampleDetailView({ id }: { id: string }) {
  const { lookups, can } = useAppData(); const router = useRouter(); const toast = useToast(); const { data, loading, error, reload } = useRemote<SampleDetailData>(`/api/samples/${encodeURIComponent(id)}`); const [moveOpen, setMoveOpen] = useState(false); const [form, setForm] = useState({ status: "active", departmentId: "", locationId: "", remark: "", note: "" }); const [saving, setSaving] = useState(false); const [copied, setCopied] = useState(false);
  useEffect(() => { if (data) setForm({ status: data.sample.status, departmentId: data.sample.departmentId || "", locationId: data.sample.locationId || "", remark: "", note: data.sample.note || "" }); }, [data]);
  if (loading) return <LoadingState />; if (error || !data) return <ErrorState message={error || "样品不存在"} retry={reload} />;
  const s = data.sample; const locations = lookups?.locations.filter((item) => item.departmentId === form.departmentId) || [];
  async function move(event: FormEvent) { event.preventDefault(); setSaving(true); try { await apiFetch(`/api/samples/${s.id}`, { method: "PATCH", body: JSON.stringify({ ...form, departmentId: form.status === "active" ? form.departmentId || null : null, locationId: form.status === "active" ? form.locationId || null : null }) }); toast("样品位置与状态已更新"); setMoveOpen(false); await reload(); } catch (reason) { toast(reason instanceof Error ? reason.message : "更新失败", "error"); } finally { setSaving(false); } }
  async function copyCode() { await navigator.clipboard.writeText(s.code); setCopied(true); window.setTimeout(() => setCopied(false), 1600); }
  async function archive() { if (!confirm("确定归档这件样品吗？归档后仍保留历史记录。")) return; try { await apiFetch(`/api/samples/${s.id}`, { method: "DELETE" }); toast("样品已归档"); router.push("/samples"); } catch (reason) { toast(reason instanceof Error ? reason.message : "归档失败", "error"); } }
  return <>
    <PageHeader eyebrow={`实物编号 ${s.code}`} title={s.productName} description={`货号 ${s.sku} · 到样 ${formatDate(s.arrivedAt)}`} actions={<><Link className="button button-ghost" href="/samples"><ArrowLeft size={17} />返回</Link>{can("samples:move") && <button className="button button-primary" onClick={() => setMoveOpen(true)}><MoveRight size={17} />修改位置 / 状态</button>}</>} />
    <section className="sample-focus-grid"><article className="panel sample-identity"><div className="sample-image-area"><ProductImage urls={s.imageUrls} alt={s.productName} size="large" /><StatusBadge status={s.status} /></div><div className="sample-identity-copy"><p className="eyebrow">当前所在位置</p><h2><MapPin size={25} />{activeLocationLabel({ status: s.status, department_name: s.departmentName, location_name: s.locationName })}</h2><button className="copy-code" onClick={copyCode}><span>{s.code}</span>{copied ? <Check size={16} /> : <Clipboard size={16} />}</button><dl><div><dt>店铺</dt><dd>{s.storeName || "—"}</dd></div><div><dt>价格 / 佣金</dt><dd>{s.price ? `¥${s.price}` : "—"}{s.commission ? ` / ${s.commission}` : ""}</dd></div><div><dt>供应链 / 机构</dt><dd>{s.supplyChain || "—"}</dd></div><div><dt>样品备注</dt><dd>{s.note || "—"}</dd></div></dl><Link className="row-link" href={`/products/${s.productId}`}>查看商品档案</Link></div></article>
      <article className="panel qr-card"><p className="eyebrow">扫码快速访问</p><h2>样品二维码</h2><img src={data.qrCode} alt={`${s.code} 二维码`} /><p>打印标签功能将在后续版本加入。当前可用手机扫码打开此样品详情。</p></article></section>
    <section className="panel timeline-panel"><header className="panel-header padded"><div><p className="eyebrow">完整追踪</p><h2>位置与状态流转记录</h2></div><Link href="/api/export?type=movements" className="button button-secondary button-compact"><Download size={16} />导出记录</Link></header><div className="timeline">{data.movements.map((movement, index) => <div className="timeline-item" key={movement.id}><div className="timeline-rail"><span>{index === 0 ? <MapPin size={15} /> : <History size={15} />}</span><i /></div><div className="timeline-content"><div><StatusBadge status={movement.toStatus} /><b>{movement.toStatus === "active" ? [movement.toDepartmentName, movement.toLocationName].filter(Boolean).join(" · ") || "位置待确认" : statusLabel(movement.toStatus)}</b></div><p>{movement.fromStatus ? `从 ${movement.fromStatus === "active" ? [movement.fromDepartmentName, movement.fromLocationName].filter(Boolean).join(" · ") || "原位置" : statusLabel(movement.fromStatus)} 更新` : "首次到样登记"}</p>{movement.remark && <blockquote>{movement.remark}</blockquote>}<small>{movement.operatorName || "系统"} · {formatDate(movement.createdAt, true)}</small></div></div>)}</div>{can("samples:archive") && s.status !== "active" && <button className="danger-link timeline-archive" onClick={archive}><Archive size={16} />归档此样品</button>}</section>
    {moveOpen && <Modal title={`更新样品 ${s.code}`} onClose={() => setMoveOpen(false)} wide><form className="modal-form" onSubmit={move}><Field label="样品状态" required><div className="status-picker">{SAMPLE_STATUSES.map((item) => <label className={form.status === item.value ? "selected" : ""} key={item.value}><input type="radio" name="status" checked={form.status === item.value} onChange={() => setForm({ ...form, status: item.value, departmentId: item.value === "active" ? form.departmentId : "", locationId: "" })} /><StatusBadge status={item.value} /><small>{item.value === "active" ? "位于公司部门或直播间" : item.label}</small></label>)}</div></Field>{form.status === "active" && <div className="form-grid"><Field label="所在部门" required><select value={form.departmentId} onChange={(event) => setForm({ ...form, departmentId: event.target.value, locationId: "" })}><option value="">请选择部门</option>{lookups?.departments.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></Field><Field label="具体位置"><select value={form.locationId} onChange={(event) => setForm({ ...form, locationId: event.target.value })}><option value="">暂不细分</option>{locations.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></Field></div>}<div className="form-grid"><Field label="本次操作备注" hint="选填"><textarea rows={3} value={form.remark} onChange={(event) => setForm({ ...form, remark: event.target.value })} placeholder="例如：A 直播间使用完，归还商务部" /></Field><Field label="样品长期备注" hint="选填"><textarea rows={3} value={form.note} onChange={(event) => setForm({ ...form, note: event.target.value })} /></Field></div><div className="modal-actions"><button type="button" className="button button-ghost" onClick={() => setMoveOpen(false)}>取消</button><button className="button button-primary" disabled={saving}>{saving ? "正在保存…" : "确认更新"}</button></div></form></Modal>}
  </>;
}

type BarcodeDetectorConstructor = new (options?: { formats?: string[] }) => { detect: (source: CanvasImageSource) => Promise<Array<{ rawValue: string }>> };

export function ScannerView() {
  const router = useRouter(); const toast = useToast(); const videoRef = useRef<HTMLVideoElement>(null); const streamRef = useRef<MediaStream | null>(null); const frameRef = useRef<number | null>(null); const [running, setRunning] = useState(false); const [manual, setManual] = useState(""); const [supported, setSupported] = useState(true);
  function stop() { if (frameRef.current) cancelAnimationFrame(frameRef.current); streamRef.current?.getTracks().forEach((track) => track.stop()); streamRef.current = null; setRunning(false); }
  useEffect(() => () => stop(), []);
  function openValue(value: string) { stop(); const cleaned = value.trim().split("/").filter(Boolean).pop() || value.trim(); if (!cleaned) return; router.push(`/samples/${encodeURIComponent(cleaned)}`); }
  async function start() { try { const Detector = (window as unknown as { BarcodeDetector?: BarcodeDetectorConstructor }).BarcodeDetector; if (!Detector) { setSupported(false); return; } const stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: { ideal: "environment" } }, audio: false }); streamRef.current = stream; if (videoRef.current) { videoRef.current.srcObject = stream; await videoRef.current.play(); } setRunning(true); const detector = new Detector({ formats: ["qr_code"] }); const scan = async () => { if (!videoRef.current || !streamRef.current) return; try { const results = await detector.detect(videoRef.current); if (results[0]?.rawValue) { openValue(results[0].rawValue); return; } } catch {} frameRef.current = requestAnimationFrame(scan); }; frameRef.current = requestAnimationFrame(scan); } catch { toast("无法使用摄像头，请检查浏览器权限或手动输入编号", "error"); setSupported(false); } }
  function submit(event: FormEvent) { event.preventDefault(); if (manual.trim()) openValue(manual); }
  return <>
    <PageHeader eyebrow="手机快捷操作" title="扫描样品二维码" description="扫码后可立即查看样品当前位置，并在有权限时完成流转。" />
    <section className="scanner-layout"><div className="panel scanner-card"><div className={`camera-frame ${running ? "running" : ""}`}><video ref={videoRef} muted playsInline /><div className="scan-corners"><i /><i /><i /><i /></div>{!running && <div className="camera-placeholder"><QrCode size={58} /><h2>将二维码放入框内</h2><p>建议使用手机后置摄像头</p></div>}</div><div className="scanner-actions">{running ? <button className="button button-secondary" onClick={stop}><X size={18} />停止扫描</button> : <button className="button button-primary" onClick={start}><Camera size={18} />打开摄像头扫码</button>}{!supported && <p className="inline-hint">当前浏览器不支持直接识别二维码，请使用下方编号查询。</p>}</div></div><div className="panel scanner-manual"><div className="scanner-icon"><Keyboard size={25} /></div><p className="eyebrow">备用方式</p><h2>输入实物编号</h2><p>二维码磨损或摄像头不可用时，可直接输入标签上的独立编号；旧编号也可继续查询。</p><form onSubmit={submit}><div className="search-box"><Search size={18} /><input value={manual} onChange={(event) => setManual(event.target.value)} placeholder="例如 HZG-2026-0001-001" /></div><button className="button button-primary" disabled={!manual.trim()}>查询样品</button></form><div className="mobile-tip"><Smartphone size={20} /><span>扫码页面需在 HTTPS 域名下使用摄像头，一键安装会自动配置。</span></div></div></section>
  </>;
}
